name: Tailscale (iso)

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt update -y
          sudo apt install curl wget qemu-kvm cpulimit -y
          sudo apt install novnc python3 websockify -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo nohup tailscaled --state=tailscaled.state &>/dev/null &
          sudo tailscale up
          sudo websockify -D --web=/usr/share/novnc --cert=novnc.pem 8080 localhost:5900
      - name: đang setup windows
        run: |
          sudo chmod 666 /dev/kvm
          echo "Setup Windows"
          sudo wget -O cdrom.iso https://pixeldrain.com/u/ao5gGTQh &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          sudo wget -O virtio-win.iso https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.248-1/virtio-win.iso &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          sudo qemu-img create -f qcow2 /mnt/disk.qcow2 64G
          echo "Done"
          echo "View Console (VNC) $(tailscale ip -4):5900"
          sudo cpulimit -l 60 -- sudo kvm -M q35,usb=on -device usb-tablet -cpu host -smp 2,threads=1,cores=2,sockets=1 -m 12G,slots=2,maxmem=16G -object memory-backend-ram,size=6G,id=m0 -object memory-backend-ram,size=6G,id=m1 -numa node,nodeid=0,memdev=m0,cpus=0 -numa node,nodeid=1,memdev=m1,cpus=1 -device virtio-balloon-pci -vga qxl -device virtio-net-pci,netdev=net0 -netdev user,id=n0,hostfwd=tcp::3389-:3389 -boot c -device virtio-serial-pci -device virtio-rng-pci -enable-kvm -drive file=/mnt/a.qcow2,if=none,id=nvme0 -device nvme,drive=nvme0,serial=cocaiconcak -drive file=file.iso,media=cdrom -drive file=a.img,format=raw,id=stick,if=none -device nec-usb-xhci,id=xhci -device usb-storage,bus=xhci.0,drive=stick -drive file=driver.iso,media=cdrom  -vnc :0 -drive file=/usr/share/ovmf/OVMF.fd,if=pflash,readonly=off -uuid e47ddb84-fb4d-46f9-b531-14bb15156336 -drive file=cdrom.iso,media=cdrom -drive file=virtio-win.iso,media=cdrom -device virtio-rng-pci
          while ps axg | grep -vw grep | grep -w qemu-system-x86_64 > /dev/null; do sleep 1; done
          while ps axg | grep -vw grep | grep -w kvm > /dev/null; do sleep 1; done
      - uses: actions/upload-artifact@v4
        with:
          name: Windows QCOW2 File
          path: /mnt/disk.qcow2
